### ISSUE TITLE
Directory name is invalid message

### ISSUE THREAD

**Issue by YetAnotherDev** [Zerg00s/MultipleTeamsInstances#1]
When running the script i was getting the following error even if the directory is correct. 

`Start-Process : This command cannot be run due to the error: The directory name is invalid.`

For me the fix was simply just adding the working directory to the start process command. This is what works for me:

`Start-Process "C:\Users\$($credential.UserName)\AppData\Local\Microsoft\Teams\Update.exe" '--processStart "Teams.exe"' -Credential $credential -WorkingDirectory $env:windir`

**Comment by Zerg00s** [comment]
@YetAnotherDev, thank you. I've merged your PR.
